# Generated by Django 5.2.4 on 2025-07-12 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_published',
            new_name='is_vip_only',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='s3_url',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_preview',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
